### ISSUE TITLE
M3: Fix any problem based on what is commented on Gradescope for Milestone 1 

### ISSUE THREAD

**Issue by AzinPiran** [UBC-MDS/airline-customer-satisfaction-predictor#43]
- [ ] You should mention the findings of your analysis in the README file.
- [ ] Abstract/Summary ---> 
What does it mean by customer satisfaction? Please state your question more clearly. Limitations of the findings were not stated (all studies have limitations).

- [ ] Results: 
Please use "Results" as the header - not "Reporting Performance". Also please include figure descriptions under your figures (should be 1-2 sentences to describe the figure for readers who only read the figure).
- Discussion : 
Can you mention some assumptions and limitations of the methods and your findings? Also, please reiterate some key findings in this part of your report.

- [ ] Spelling and Grammar: 
If there are acronyms in your report, you should explain what they mean (ROC, SHAP, ...). Also try to avoid bullet points in your report.

- [ ] Reproducibility : Good job on the documentation, but please expand how to use the project, how to run the analysis (not just installing the dependencies and activating the environment). I also got this error from running your conda-lock install instruction: "ValueError: Neither prefix, nor name provided." which means you need to specify either: the environment name or the path to the environment
